[general]
import = [
    "~/.cache/wal/colors-alacritty.toml"
]

[env]
TERM = "xterm-256color"

[terminal]
shell = "/usr/bin/bash"

[window]
dynamic_padding = false

padding.x = 5
padding.y = 5

decorations= "buttonless"

[font]
size = 14
